name: test
on:
  push:
  pull_request:
jobs:
  test:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run test
      uses: cedrickring/golang-action@1.5.2
      with:
        args: make test
